Dominion::Card.define "Baron"
Dominion::Card.define "Bridge"
Dominion::Card.define "Conspirator"
Dominion::Card.define "Coppersmith"
Dominion::Card.define "Courtyard"
Dominion::Card.define "Duke"
Dominion::Card.define "Great Hall"
Dominion::Card.define "Harem"
Dominion::Card.define "Ironworks"
Dominion::Card.define "Masquerade"
Dominion::Card.define "Mining Village"
Dominion::Card.define "Minion"
Dominion::Card.define "Nobles"
Dominion::Card.define "Pawn"
Dominion::Card.define "Saboteur"
Dominion::Card.define "Scout"
Dominion::Card.define "Secret Chamber"
Dominion::Card.define "Shanty Town"
Dominion::Card.define "Steward"
Dominion::Card.define "Swindler"
Dominion::Card.define "Torturer"
Dominion::Card.define "Trading Post"
Dominion::Card.define "Tribute"
Dominion::Card.define "Upgrade"
Dominion::Card.define "Wishing Well"
