Dominion::Card.define "Ambassador"
Dominion::Card.define "Bazaar"
Dominion::Card.define "Caravan"
Dominion::Card.define "Cutpurse"
Dominion::Card.define "Embargo"
Dominion::Card.define "Explorer"
Dominion::Card.define "Fishing Village"
Dominion::Card.define "Ghost Ship"
Dominion::Card.define "Haven"
Dominion::Card.define "Island"
Dominion::Card.define "Lighthouse"
Dominion::Card.define "Lookout"
Dominion::Card.define "Merchant Ship"
Dominion::Card.define "Native Village"
Dominion::Card.define "Navigator"
Dominion::Card.define "Outpost"
Dominion::Card.define "Pearl Diver"
Dominion::Card.define "Pirate Ship"
Dominion::Card.define "Salvager"
Dominion::Card.define "Sea Hag"
Dominion::Card.define "Smugglers"
Dominion::Card.define "Tactician"
Dominion::Card.define "Treasure Map"
Dominion::Card.define "Treasury"
Dominion::Card.define "Warehouse"
Dominion::Card.define "Wharf"
